version: "3.4"

services:
  app:
    image: ecommerce-service:1.0
    container_name: ecommerce-service
    volumes:
      - .docker/data/app:/app/logs
      - ./:/app # mount từ môi trường gốc vào trong để nếu  bạn thay đổi code thì bên trong sẽ tự động cập nhật
    ports:
      - 3055:3055
    restart: unless-stopped
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: ec-mongodb
    ports:
      - 27017:27017
    environment:
      #- MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # named volumes
      - .docker/data/mongodb:/data/db
    restart: unless-stopped